master:
  hostname: 3.94.65.26
  user: root
  deploy_path: /opt/easyengine/sites/ee-workshop.tangence.com/app/htdocs

develop:
  hostname: hcl-dev.ext.rt.gw
  user: root
  deploy_path: /opt/easyengine/sites/glovius-2020.hcl-dev.ext.rt.gw/app/htdocs
