master:
  hostname: 50.17.160.169
  user: root
  deploy_path: /opt/easyengine/sites/www.glovius.com/app/htdocs

develop:
  hostname: hcl-dev.ext.rt.gw
  user: root
  deploy_path: /opt/easyengine/sites/glovius-2020.hcl-dev.ext.rt.gw/app/htdocs
